### PR TITLE
Updates based on feedback from @tmigot

### PR DESCRIPTION
**Pull request by abelsiqueira**
Based on comments made on https://github.com/JuliaSmoothOptimizers/JSOSuite.jl/pull/163 by @tmigot.

### CODE REVIEW

**Comment by abelsiqueira** [comment]
@tmigot, can you review?

**Review by tmigot — APPROVED** [review]
LGTM, thanks!

**Comment by abelsiqueira** [comment]
@allcontributors please add @tmigot for feedback

**Comment by abelsiqueira** [comment]
@allcontributors please add @tmigot for review

**Pull request merged**
